html:
  sidebar:
    groupOrder: "auto"
  stylesheets:
    - assets/css/style.css
  playground:
    enabled: true
    env: production
    environments:
      production:
        url: https://api.odus.ai/v1
        auth:
          name: apikey
          options:
            key: yV_Y_mSKBkbCbdsw7S64oVnm5tGRQoQRuQNPoHPCU40
            header: X-Api-Key