html:
  sidebar:
    groupOrder: "auto"
  playground:
    enabled: true
    env: development
    environments:
      development:
        url: http://127.0.0.1:8000/v1
        auth:
          name: apikey
          options:
            key: yV_Y_mSKBkbCbdsw7S64oVnm5tGRQoQRuQNPoHPCU40
            header: X-AUTH-TOKEN
      staging:
        url: https://he110.odus.ai/v1
        auth:
          name: apikey
          options:
            key: yV_Y_mSKBkbCbdsw7S64oVnm5tGRQoQRuQNPoHPCU40
            header: X-AUTH-TOKEN
      production:
        url: https://api.odus.ai/v1
        auth:
          name: apikey
          options:
            key: yV_Y_mSKBkbCbdsw7S64oVnm5tGRQoQRuQNPoHPCU40
            header: X-AUTH-TOKEN