### List [GET]
+ Parameters
    + botId (number) - Uniq bot ID
+ Response 200 (application/json)
    + Attributes (array[Client])

### Filtered list [POST]
+ Parameters
    + botId (number) - Uniq bot ID
+ Request (application/json)
    + Attributes
        + locale: `US` (string, optional)
        + channel: `fb` (string, optional)
        + limit (number, optional)
            + Default: 20
        + offset: 0 (number, optional)
            + Default: 0

+ Response 200 (application/json)
    + Attributes (array[Client])

### Get [GET /{clientId}]
+ Parameters
    + botId (number) - Uniq bot ID
    + clientId: 999 (number, required) - Uniq client ID

+ Response 200 (application/json)
    + Attributes (Client)

### Delete [DELETE /{clientId}]
+ Parameters
    + botId (number) - Uniq bot ID
    + clientId: 999 (number, required) - Uniq client ID

+ Response 200 (application/json)
    + Attributes (Client)