### E_SegmentNotFound
+ code: `segment_not_found` (string)
+ message: `Segment doesn't exist` (string)

### E_ClientNotFound
+ code: `client_not_found` (string)
+ message: `Client doesn't exist` (string)

### E_ChannelNotConfigured
+ code: `channel_not_configured`
+ message: `Requested channel not configured`