### Text [POST /client/{clientId}/channel/{chennelType}]
+ Parameters
    + clientId: 999 (number, required) - Uniq client ID
    + chennelType: `fb` (string, required) - Chosen channel type

+ Request (application/json)
    + Attributes (Message)
        + message: `Buttons and attachment are optional. If you don't want to use it, just set to null`
        + buttons: null
        + attachment: null

+ Response 200 (application/json)
    + Attributes
        + message (Message)
            + message: `Buttons and attachment are optional. If you don't want to use it, just set to null`
            + buttons: null
            + attachment: null
        + client (Client)
        + channel (Channel)
            + type: `fb`
        
+ Response 404 (application/json)
    + Attributes
        + error (E_ClientNotFound)

+ Response 400 (application/json)
    + Attributes
        + error (E_ChannelNotConfigured)

### Buttons [POST /client/{clientId}/channel/{chennelType}]
+ Parameters
    + clientId: 999 (number, required) - Uniq client ID
    + chennelType: `fb` (string, required) - Chosen channel type

+ Request (application/json)
    + Attributes (Message)
        + message: `Message can't be empty!`
        + buttons (array[Button])
            - (Button)
                + type: `link`
                + title: `This is url button`
                + target: `https://odus.ai/`
            - (Button)
                + type: `answer`
                + title: `Redirect to answer-block`
                + target: `15`
            - (Button)
                + type: `form`
                + title: `Redirect to form-block`
                + target: `50`
        + attachment: null

+ Response 200 (application/json)
    + Attributes
        + message (Message)
            + message: `Message can't be empty!`
            + buttons (array[Button])
                - (Button)
                    + type: `link`
                    + title: `This is url button`
                    + target: `https://odus.ai/`
                - (Button)
                    + type: `answer`
                    + title: `Redirect to answer-block`
                    + target: `15`
                - (Button)
                    + type: `form`
                    + title: `Redirect to form-block`
                    + target: `50`
            + attachment: null
        + client (Client)
        + channel (Channel)
            + type: `fb`
        
+ Response 404 (application/json)
    + Attributes
        + error (E_ClientNotFound)

+ Response 400 (application/json)
    + Attributes
        + error (E_ChannelNotConfigured)

### Attachment [POST /client/{clientId}/channel/{chennelType}]

This method allows to send any attachments, but requires url of file. If you need to upload your own file read ['Upload file'](https://google.com)

+ Parameters
    + clientId: 999 (number, required) - Uniq client ID
    + chennelType: `fb` (string, required) - Chosen channel type

+ Request (application/json)
    + Attributes (Message)
        + message: `Message can be empty in this case. Just set it to null`
        + buttons: null
        + attachment (Attachment)
            + type: `image`
            + url: `https://odus.ai/img/header/2x/logo.png`

+ Response 200 (application/json)
    + Attributes
        + message (Message)
            + message: `Message can be empty in this case. Just set it to null`
            + buttons: null
            + attachment (Attachment)
                + type: `image`
                + url: `https://odus.ai/img/header/2x/logo.png`
        + client (Client)
        + channel (Channel)
            + type: `fb`
        
+ Response 404 (application/json)
    + Attributes
        + error (E_ClientNotFound)

+ Response 400 (application/json)
    + Attributes
        + error (E_ChannelNotConfigured)