### List [GET]
+ Response 200 (application/json)
    + Attributes (array[Segment])

### Get [GET /segment/{id}]
+ Parameters
    + id: 1050 (number, required) - Uniq segment ID

+ Response 200 (application/json)
    + Attributes (Segment)

### Delete [DELETE /segment/{id}]
+ Parameters
    + id: 1050 (number, required) - Uniq segment ID

+ Response 200 (application/json)
    + Attributes (Segment)

### Add client [PUT /segment/{segmentId}/client/{clientId}]
+ Parameters
    + segmentId: 1050 (number, required) - Uniq segment ID
    + clientId: 999 (number, required) - Uniq client ID

+ Response 200 (application/json)
    + Attributes
        + segment (Segment)
        + client (Client)

+ Response 404 (application/json)
    + Attributes
        + error (E_SegmentNotFound)

+ Response 404 (application/json)
    + Attributes
        + error (E_ClientNotFound)

### Remove client [DELETE /segment/{segmentId}/client/{clientId}]
+ Parameters
    + segmentId: 1050 (number, required) - Uniq segment ID
    + clientId: 999 (number, required) - Uniq client ID

+ Response 200 (application/json)
    + Attributes
        + segment (Segment)
        + client (Client)

+ Response 404 (application/json)
    + Attributes
        + error (E_SegmentNotFound)

+ Response 404 (application/json)
    + Attributes
        + error (E_ClientNotFound)