### List [GET]
+ Parameters
    + botId (number) - Uniq bot ID
+ Response 200 (application/json)
    + Attributes (array[Segment])

### Get [GET /{segmentId}]
+ Parameters
    + botId (number) - Uniq bot ID
    + segmentId: 1050 (number, required) - Uniq segment ID

+ Response 200 (application/json)
    + Attributes (Segment)

### Delete [DELETE /{segmentId}]
+ Parameters
    + botId (number) - Uniq bot ID
    + segmentId: 1050 (number, required) - Uniq segment ID

+ Response 200 (application/json)
    + Attributes (Segment)

### Add client [PUT /{segmentId}/client/{clientId}]
+ Parameters
    + botId (number) - Uniq bot ID
    + segmentId: 1050 (number, required) - Uniq segment ID
    + clientId: 999 (number, required) - Uniq client ID

+ Response 200 (application/json)
    + Attributes
        + segment (Segment)
        + client (Client)

+ Response 404 (application/json)
    + Attributes
        + error (E_SegmentNotFound)

+ Response 404 (application/json)
    + Attributes
        + error (E_ClientNotFound)

### Remove client [DELETE /{segmentId}/client/{clientId}]
+ Parameters
    + botId (number) - Uniq bot ID
    + segmentId: 1050 (number, required) - Uniq segment ID
    + clientId: 999 (number, required) - Uniq client ID

+ Response 200 (application/json)
    + Attributes
        + segment (Segment)
        + client (Client)

+ Response 404 (application/json)
    + Attributes
        + error (E_SegmentNotFound)

+ Response 404 (application/json)
    + Attributes
        + error (E_ClientNotFound)