### Bot
+ id: 105 (number) - Uniq bot ID
+ name: `API Demo bot` (string) - Your bot's name
+ avatar: `https://panel.odus.ai/bots/81/bot_file_3b672035fbed7a9d93c691469a6a75a1.png` (string, optional) - Url of bot's avatar or null

### Client
+ id: 999 (number) - Uniq client ID
+ name: `James E. Herman` (string) - Client's name
+ locale: `US` (string, optional) - Locale code (ISO 639-1), if detected 
+ signed_up: `2014-11-11T08:40:51.620Z` (string) - Date and time, when client signed signed up 
+ last_seen:` 2014-11-11T05:30:51.620Z` (string) - Date and time, when client was online
+ segments (array[Segment]) - Client's segments
+ channels (array[Channel])

### Segment
+ id: 1050 (number) - Uniq segment ID
+ name: `Customers` (string, required) - Segment's name
+ description: `Those users who bought something at least once` (string, optional) - Description
+ users: 67 (number) - Amount of users in segment

### Channel
+ type (enum, required)
    - fb (string) - Facebook
    - tg (string) - Telegram
    - vk (string) - Vkontakte
    - wa (string) - WhatsApp
    - vox (string) - VoxImplant
    - web (string) - Web-widget or landing page-bot
+ is_configured: true (boolean, required) - Is channel configured for bot or already deleted

### Message
+ message: `Simple text example` (string, optional) - Your message
+ attachment (Attachment, optional, nullable) - Attachent url, if required 
+ buttons (array[Button], optional, nullable) - Buttons

### Button
+ type (enum, required)
    - text
    - link
    - answer
    - form
+ title: `Button title` (string, required) - Text of button
+ target: (string, optional, nullable)

### Attachment
+ type (enum, required)
    - image
    - file
+ url: (string, required) - Url of file

<!-- include(exceptions.apib) -->